#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
Slim DRC regression runner for the interposer, following the IHP-SG13G2
`testing/` convention: unit testcases live in `testcases/unit/<table>.gds`, each
top cell is run through its deck and the set of violated rules is compared
against the reference ("golden") expectation declared below.

This reuses the interposer's own `run_drc.run_deck` / `get_rules_with_violations`
(one klayout -b invocation per top cell) instead of a standalone harness, so the
DRC tests are exercised through the same runner as sign-off.

Testcase GDS files are regenerated by the `gen_*` scripts in `testcases/unit/`.

Usage:
    python run_regression.py                 # run all tables
    python run_regression.py --table via4    # run one table
"""

import argparse
import sys
from pathlib import Path

import klayout.db as db

# Reference expectations: table -> {deck, cells: {top_cell: expected_violated_rule_set}}.
# A clean cell must yield an empty set (also guards against false positives on the
# other rules of that deck); a violation cell must yield exactly its rule set.
GOLDEN = {
    'via4': {
        'deck': 'via4',
        'cells': {
            'via4_viol':  {'V4.b1', 'V4.c1', 'M5.c1'},
            'via4_clean': set(),
        },
    },
}


def run_table(table: str, spec: dict, unit_dir: Path, run_dir: Path,
              run_deck, get_rules_with_violations, drc_script: str) -> bool:
    gds = unit_dir / f"{table}.gds"
    if not gds.is_file():
        print(f"  FAIL {table}: testcase not found: {gds} (run gen_{table}_testcase.py)")
        return False

    layout = db.Layout()
    layout.read(str(gds))
    present = {c.name for c in layout.each_cell()}

    ok = True
    for cell, expected in spec['cells'].items():
        if cell not in present:
            print(f"  FAIL {table}/{cell}: top cell missing from {gds.name}")
            ok = False
            continue
        report = run_deck(drc_script, spec['deck'], str(gds), cell,
                          run_dir, threads=2, run_mode="flat")
        violated = get_rules_with_violations(report)
        if violated == expected:
            print(f"  PASS {table}/{cell}: {sorted(expected) if expected else 'clean'}")
        else:
            missing = expected - violated
            extra = violated - expected
            detail = []
            if missing:
                detail.append(f"missing {sorted(missing)}")
            if extra:
                detail.append(f"unexpected {sorted(extra)}")
            print(f"  FAIL {table}/{cell}: {', '.join(detail)} (got {sorted(violated)})")
            ok = False
    return ok


def main():
    parser = argparse.ArgumentParser(description="Interposer DRC regression runner")
    parser.add_argument("--table", default=None,
                        help="Run a single rule table (default: all). e.g. --table via4")
    args = parser.parse_args()

    testing_dir = Path(__file__).resolve().parent
    drc_dir = testing_dir.parent                       # .../tech/drc
    unit_dir = testing_dir / "testcases" / "unit"
    run_dir = testing_dir / "regression_run"
    run_dir.mkdir(exist_ok=True)

    sys.path.insert(0, str(drc_dir))
    from run_drc import run_deck, get_rules_with_violations
    drc_script = str(drc_dir / "intm4tm2.drc")

    tables = {args.table: GOLDEN[args.table]} if args.table else GOLDEN
    if args.table and args.table not in GOLDEN:
        print(f"Unknown table '{args.table}'. Available: {', '.join(GOLDEN)}")
        return 2

    print("Running DRC regression:")
    all_ok = True
    for table, spec in tables.items():
        all_ok &= run_table(table, spec, unit_dir, run_dir,
                            run_deck, get_rules_with_violations, drc_script)

    if all_ok:
        print("\nAll DRC regression checks passed.")
        return 0
    print("\nDRC regression FAILED")
    return 1


if __name__ == "__main__":
    sys.exit(main())
