#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
Slim DRC regression runner for the interposer, following the IHP-SG13G2
`testing/` convention: unit testcases live in `testcases/unit/<table>.gds`, each
top cell is run through its deck and the set of violated rules is compared
against the reference ("golden") expectation declared below.

This reuses the interposer's own `run_drc.run_deck` / `get_rules_with_violations`
(one klayout -b invocation per top cell) instead of a standalone harness, so the
DRC tests are exercised through the same runner as sign-off.

Testcase GDS files are regenerated by the `gen_*` scripts in `testcases/unit/`.

Usage:
    python run_regression.py                 # run all tables
    python run_regression.py --table via4    # run one table
"""

import argparse
import subprocess
import sys
from pathlib import Path

import klayout.db as db

# ---------------------------------------------------------------------------
# Provenance pin -- canonical run configuration the GOLDEN sets were validated
# under. The GOLDEN marker sets were captured under exactly ONE KLayout version
# and ONE run_mode/thread configuration; a different KLayout, run_mode or thread
# count can shift which markers a deck emits, and a mismatched-but-self-
# consistent run would still compare green against GOLDEN. So the run is pinned
# to that configuration, never merely recorded.
#
# The two halves are pinned differently, and the difference is deliberate.
# run_mode and threads are pinned BY CONSTRUCTION: run_table passes the
# constants below to every deck run and nothing can vary them, so there is
# nothing left to assert. The KLayout version is the half that can drift under
# the run, so it is the half asserted at startup (a cheap metadata check, not a
# second regression), and it is read from the BINARY that produces the markers,
# never from the like-named Python module.
#
# CANONICAL_KLAYOUT_VERSION must track the ecosystem pin: the CI env in
# .github/workflows/tests.yml sets KLAYOUT_VERSION="0.30.5". run_table below
# takes its run_mode/threads from these constants, so there is exactly one
# authority for all three.
CANONICAL_KLAYOUT_VERSION = "0.30.5"
CANONICAL_RUN_MODE = "flat"
CANONICAL_THREADS = 2


def _detect_klayout_version():
    """Read the version of the KLayout BINARY the deck runs will spawn.

    The markers GOLDEN is compared against are produced by the `klayout`
    binary: run_drc.run_deck builds `["klayout", "-b", "-r", ...]` and each
    deck runs in that subprocess. The pip `klayout` Python module is a
    different artefact that merely shares the name, and the two routinely
    differ on one host, so reading the module proves nothing about the run: it
    can refuse a correct setup and it can pass a mismatched one. Read the
    producer.

    Returns the version string, or None if it cannot be read at all (no binary
    on PATH, no output, unparseable output). None is a fail-closed signal for
    assert_canonical_config; it is never treated as a match.
    """
    try:
        completed = subprocess.run(
            ["klayout", "-b", "-v"],
            capture_output=True, text=True, timeout=60,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    output = (completed.stdout or "").strip()
    if not output:
        return None
    # `klayout -b -v` prints e.g. "KLayout 0.30.5"; the version is the last field.
    return output.split()[-1] or None


def assert_canonical_config(running_version):
    """Fail loudly unless the running KLayout is the pinned one.

    run_mode and threads are not arguments here on purpose: run_table passes
    CANONICAL_RUN_MODE and CANONICAL_THREADS to every deck run and the CLI
    exposes no way to change them, so a check against those same constants
    could never fail and would be a check that does not discriminate. If either
    ever becomes configurable, this assertion must take the value the run will
    actually use, not the constant.

    Args:
        running_version: the version of the KLayout binary the runs will spawn,
            or None when it could not be determined (fail closed).

    Raises:
        RuntimeError naming BOTH the expected and the actual value on any
        divergence, and on an undeterminable version. Never warns-and-continues.
    """
    if not running_version:
        raise RuntimeError(
            "provenance pin: could not determine the running KLayout version "
            f"(expected {CANONICAL_KLAYOUT_VERSION!r}). Refusing to compare "
            "against GOLDEN under an unknown KLayout; put the pinned 'klayout' "
            "binary on PATH and re-run.")
    if running_version != CANONICAL_KLAYOUT_VERSION:
        raise RuntimeError(
            f"provenance pin: running KLayout version {running_version!r} != "
            f"pinned {CANONICAL_KLAYOUT_VERSION!r}. GOLDEN was validated under "
            "the pinned version; a different KLayout can shift deck markers and "
            "pass a mismatched run green. Install the pinned KLayout, or update "
            "GOLDEN and the pin together in the same change.")

# Reference expectations: table -> {deck, cells: {top_cell: expected_violated_rule_set}}.
# A clean cell must yield an empty set (also guards against false positives on the
# other rules of that deck); a violation cell must yield exactly its rule set.
# The optional 'defines' key maps a top cell to extra `-rd key=value` defines for
# its run (e.g. density_sanity=true for the DEN.BND.* boundary sanity rules).
GOLDEN = {
    'angle': {
        'deck': 'angle',
        'cells': {
            'angle_viol':  {'via4_drw_Angle90', 'metal4_drw_Angle45', 'metal4_drw_Acute',
                            'topmetal2_drw_Acute', 'topmetal2_drw_Angle45'},
            'angle_clean': set(),
        },
    },
    'copperpillar': {
        'deck': 'copperpillar',
        'cells': {
            'copperpillar_viol':  {'Padc.a', 'Padc.b', 'Padc.c',
                                   'Padc.d', 'Padc.f'},
            'copperpillar_clean': set(),
        },
    },
    'density': {
        'deck': 'density',
        'cells': {
            'density_viol': {'M4.j', 'M4Fil.h', 'M5.k', 'M5Fil.k', 'TM1.c', 'TM2.d',
                             'LBE.i', 'Slt.i_M4'},
            'density_clean': set(),
            'density_sanity_viol': {'DEN.BND.1', 'DEN.BND.2', 'DEN.BND.3'},
            'density_sanity_clean': set(),
        },
        'defines': {
            'density_sanity_viol': {'density_sanity': 'true'},
            'density_sanity_clean': {'density_sanity': 'true'},
        },
    },
    'lbe': {
        'deck': 'lbe',
        'cells': {
            'lbe_viol':  {'LBE.b2', 'LBE.e.dfPad', 'LBE.e.Passiv'},
            'lbe_clean': set(),
        },
    },
    'metaln': {
        'deck': 'metaln',
        'cells': {
            'metaln_viol':  {'M4.e', 'M4.f', 'M4.g', 'M4.i',
                             'M5.e', 'M5.f', 'M5.g', 'M5.i'},
            'metaln_clean': set(),
        },
    },
    'metalnfiller': {
        'deck': 'metalnfiller',
        'cells': {
            'metalnfiller_viol':  {'M4Fil.c', 'M4Fil.a2', 'M5Fil.c', 'M5Fil.a2'},
            'metalnfiller_clean': set(),
        },
    },
    'metalslits': {
        'deck': 'metalslits',
        'cells': {
            'metalslits_viol': {
                'Slt.a_M4', 'Slt.a_M5', 'Slt.a_TM1', 'Slt.a_TM2',
                'Slt.b_M4', 'Slt.b_M5', 'Slt.b_TM1', 'Slt.b_TM2',
                'Slt.c_M4', 'Slt.c_M5', 'Slt.c_TM1', 'Slt.c_TM2',
                'Slt.e_M4', 'Slt.e_M5', 'Slt.e_TM1', 'Slt.e_TM2',
                'Slt.e1_M4', 'Slt.e1_M5', 'Slt.e1_TM1', 'Slt.e1_TM2',
                'Slt.f_M4', 'Slt.f_M5', 'Slt.f_TM1', 'Slt.f_TM2',
                'Slt.g_M5', 'Slt.g_TM1',
                'Slt.h2_M4', 'Slt.h2_M5', 'Slt.h3', 'Slt.h4',
            },
            'metalslits_clean': set(),
        },
    },
    'mim': {
        'deck': 'mim',
        'cells': {
            'mim_viol':  {'MIM.a', 'MIM.b', 'MIM.c', 'MIM.d', 'MIM.e',
                          'MIM.f', 'MIM.g', 'MIM.h', 'MIM.gR'},
            'mim_clean': set(),
        },
    },
    'offgrid': {
        'deck': 'offgrid',
        'cells': {
            'offgrid_viol':  {'metal4_drw_Offgrid', 'via4_drw_Offgrid', 'topmetal2_drw_Offgrid'},
            'offgrid_clean': set(),
        },
    },
    'pad': {
        'deck': 'pad',
        'cells': {
            'pad_viol':  {'Pad.dR'},
            'pad_clean': set(),
        },
    },
    'sealring': {
        'deck': 'sealring',
        'cells': {
            'sealring_viol':  {'Seal.k', 'Seal.l', 'Seal.m', 'Seal.n'},
            'sealring_clean': set(),
        },
    },
    'solderbump': {
        'deck': 'solderbump',
        'cells': {
            'solderbump_viol':  {'Padb.a', 'Padb.b', 'Padb.c', 'Padb.d',
                                 'Padb.f'},
            'solderbump_clean': set(),
        },
    },
    'ubm_floor': {
        'deck': 'ubm_floor',
        'cells': {
            'ubm_floor_viol':  {'PadU.w', 'PadU.s'},
            'ubm_floor_clean': set(),
        },
    },
    'topmetal1filler': {
        'deck': 'topmetal1filler',
        'cells': {
            'topmetal1filler_viol':  {'TM1Fil.c', 'TM1Fil.a1', 'TM1Fil.b'},
            'topmetal1filler_clean': set(),
        },
    },
    'topmetal2': {
        'deck': 'topmetal2',
        'cells': {
            'topmetal2_viol':  {'TM2.bR'},
            'topmetal2_clean': set(),
        },
    },
    'topmetal2filler': {
        'deck': 'topmetal2filler',
        'cells': {
            'topmetal2filler_viol':  {'TM2Fil.c', 'TM2Fil.a1', 'TM2Fil.b'},
            'topmetal2filler_clean': set(),
        },
    },
    'via4': {
        'deck': 'via4',
        'cells': {
            'via4_viol':  {'V4.b1', 'V4.c1', 'M5.c1'},
            'via4_clean': set(),
        },
    },
}


def run_table(table: str, spec: dict, unit_dir: Path, run_dir: Path,
              run_deck, get_rules_with_violations, drc_script: str) -> bool:
    gds = unit_dir / f"{table}.gds"
    if not gds.is_file():
        print(f"  FAIL {table}: testcase not found: {gds} (run gen_{table}_testcase.py)")
        return False

    layout = db.Layout()
    layout.read(str(gds))
    present = {c.name for c in layout.each_cell()}

    ok = True
    for cell, expected in spec['cells'].items():
        if cell not in present:
            print(f"  FAIL {table}/{cell}: top cell missing from {gds.name}")
            ok = False
            continue
        extra_defines = spec.get('defines', {}).get(cell)
        report = run_deck(drc_script, spec['deck'], str(gds), cell,
                          run_dir, threads=CANONICAL_THREADS,
                          run_mode=CANONICAL_RUN_MODE,
                          extra_defines=extra_defines)
        violated = get_rules_with_violations(report)
        if violated == expected:
            print(f"  PASS {table}/{cell}: {sorted(expected) if expected else 'clean'}")
        else:
            missing = expected - violated
            extra = violated - expected
            detail = []
            if missing:
                detail.append(f"missing {sorted(missing)}")
            if extra:
                detail.append(f"unexpected {sorted(extra)}")
            print(f"  FAIL {table}/{cell}: {', '.join(detail)} (got {sorted(violated)})")
            ok = False
    return ok


def main():
    parser = argparse.ArgumentParser(description="Interposer DRC regression runner")
    parser.add_argument("--table", default=None,
                        help="Run a single rule table (default: all). e.g. --table via4")
    args = parser.parse_args()

    # Provenance pin: verify the running KLayout and the run configuration match
    # the canonical one GOLDEN was validated under, BEFORE running any table. On
    # any divergence this raises (naming expected vs actual) rather than letting
    # a mismatched-but-self-consistent run pass green.
    running_version = _detect_klayout_version()
    assert_canonical_config(running_version)
    print(f"Provenance pin OK: KLayout {running_version}, "
          f"run_mode={CANONICAL_RUN_MODE}, threads={CANONICAL_THREADS}")

    testing_dir = Path(__file__).resolve().parent
    drc_dir = testing_dir.parent                       # .../tech/drc
    unit_dir = testing_dir / "testcases" / "unit"
    run_dir = testing_dir / "regression_run"
    run_dir.mkdir(exist_ok=True)

    sys.path.insert(0, str(drc_dir))
    from run_drc import run_deck, get_rules_with_violations
    drc_script = str(drc_dir / "intm4tm2.drc")

    tables = {args.table: GOLDEN[args.table]} if args.table else GOLDEN
    if args.table and args.table not in GOLDEN:
        print(f"Unknown table '{args.table}'. Available: {', '.join(GOLDEN)}")
        return 2

    print("Running DRC regression:")
    all_ok = True
    for table, spec in tables.items():
        all_ok &= run_table(table, spec, unit_dir, run_dir,
                            run_deck, get_rules_with_violations, drc_script)

    if all_ok:
        print("\nAll DRC regression checks passed.")
        return 0
    print("\nDRC regression FAILED")
    return 1


if __name__ == "__main__":
    sys.exit(main())
