#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
Slim LVS regression runner for the interposer, following the IHP-SG13G2
`lvs/testing/` convention: small connectivity fixtures live in
`testcases/unit/*.gds` and are run through the interposer LVS deck; the
connectivity verdict is compared against the reference ("golden") expectation
declared below.

The interposer LVS deck is connectivity-only (labeled-net extraction, open/short
detection, optional netlist match), so this checks the deck's textual verdict
rather than a full device netlist compare.

Fixtures are regenerated by `testcases/unit/gen_lvs_connectivity_testcase.py`.

Usage:
    python run_regression.py                 # run all fixtures
    python run_regression.py --case open     # run one fixture
"""

import argparse
import subprocess
import sys
from pathlib import Path

# Fixture -> expected connectivity verdict.
#   open  : deck must report "Connectivity OPEN" (split label)
#   short : deck must report "Connectivity SHORT" (bridged labels)
#   match : when a reference schematic is given, "LVS netlists match" is required
# A clean fixture must have neither open nor short and must match its reference.
GOLDEN = {
    'clean': {
        'gds': 'lvs_clean.gds',
        'schematic': 'lvs_clean_reference.cir',
        'open': False,
        'short': False,
        'match': True,
    },
    'open': {
        'gds': 'lvs_open.gds',
        'open': True,
        'short': False,
    },
    'short': {
        'gds': 'lvs_short.gds',
        'open': False,
        'short': True,
    },
}


def run_lvs(lvs_deck: Path, gds_path: Path, run_dir: Path, schematic: Path = None):
    """Run the LVS deck in KLayout batch mode and return combined stdout+stderr."""
    cmd = [
        "klayout", "-b", "-r", str(lvs_deck),
        "-rd", f"input={gds_path}",
        "-rd", "top_lvl_pins=true",
    ]
    if schematic is not None:
        cmd += ["-rd", f"schematic={schematic}"]
        cmd += ["-rd", f"report={run_dir / (gds_path.stem + '.lvsdb')}"]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
    return result.stdout + result.stderr


def run_case(case: str, spec: dict, unit_dir: Path, run_dir: Path,
             lvs_deck: Path) -> bool:
    gds = unit_dir / spec['gds']
    if not gds.is_file():
        print(f"  FAIL {case}: fixture not found: {gds} "
              f"(run gen_lvs_connectivity_testcase.py)")
        return False

    schematic = unit_dir / spec['schematic'] if spec.get('schematic') else None
    out = run_lvs(lvs_deck, gds, run_dir, schematic=schematic)

    problems = []
    has_open = "Connectivity OPEN" in out
    has_short = "Connectivity SHORT" in out
    if has_open != spec['open']:
        problems.append(f"open={has_open} (expected {spec['open']})")
    if has_short != spec['short']:
        problems.append(f"short={has_short} (expected {spec['short']})")
    if spec.get('match'):
        if "LVS netlists match" not in out:
            problems.append("reference netlist did not match")

    if problems:
        print(f"  FAIL {case}: {', '.join(problems)}")
        return False
    verdict = ('open' if spec['open'] else
               'short' if spec['short'] else
               'clean+match' if spec.get('match') else 'clean')
    print(f"  PASS {case}: {verdict}")
    return True


def main():
    parser = argparse.ArgumentParser(description="Interposer LVS regression runner")
    parser.add_argument("--case", default=None,
                        help="Run a single fixture (default: all). e.g. --case open")
    args = parser.parse_args()

    testing_dir = Path(__file__).resolve().parent
    lvs_dir = testing_dir.parent                       # .../tech/lvs
    unit_dir = testing_dir / "testcases" / "unit"
    run_dir = testing_dir / "regression_run"
    run_dir.mkdir(exist_ok=True)
    lvs_deck = lvs_dir / "intm4tm2.lvs"

    if args.case and args.case not in GOLDEN:
        print(f"Unknown case '{args.case}'. Available: {', '.join(GOLDEN)}")
        return 2
    cases = {args.case: GOLDEN[args.case]} if args.case else GOLDEN

    print("Running LVS regression:")
    all_ok = True
    for case, spec in cases.items():
        all_ok &= run_case(case, spec, unit_dir, run_dir, lvs_deck)

    if all_ok:
        print("\nAll LVS regression checks passed.")
        return 0
    print("\nLVS regression FAILED")
    return 1


if __name__ == "__main__":
    sys.exit(main())
